//
//  CheckCodeViewController.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import CBPinEntryView

final class CheckCodeViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CheckCodePresenterInterface!
    var number: String!

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var pinEntryView: CBPinEntryView!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        
        configurePinEntryView()
        configureTitle()
        setTitle(title: "Регистрация")
    }
    
    private func configurePinEntryView() {
        pinEntryView.becomeFirstResponder()
        pinEntryView.allowedEntryTypes = .numerical
        pinEntryView.keyboardType = 4
        pinEntryView.delegate = self
    }
    
    private func configureTitle() {
        titleLabel.text = "Введите код, отправленный на номер \(number!)"
    }
	
}

// MARK: - Extensions -

extension CheckCodeViewController: CheckCodeViewInterface {
    
    func setError() {
        pinEntryView.setError(isError: true)
    }
}

extension CheckCodeViewController: CBPinEntryViewDelegate {
    func entryChanged(_ completed: Bool) {
        pinEntryView.setError(isError: false)
    }
    
    func entryCompleted(with entry: String?) {
        presenter.signIn(code: entry!)
    }
}
