//
//  CheckCodeInterfaces.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CheckCodeWireframeInterface: WireframeInterface {
    func routeToCreateUser()
}

protocol CheckCodeViewInterface: ViewInterface {
    func setError()
}

protocol CheckCodePresenterInterface: PresenterInterface {
    func signIn(code: String)
}

protocol CheckCodeInteractorInterface: InteractorInterface {
    func signIn(code: String, result: @escaping (Error?) -> ())
}
