//
//  CheckCodeInteractor.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import FirebaseAuth

final class CheckCodeInteractor {
}

// MARK: - Extensions -

extension CheckCodeInteractor: CheckCodeInteractorInterface {
    func signIn(code: String, result: @escaping (Error?) -> ()) {
        let verificationID = UserDefaults.standard.string(forKey: "authVerificationID")!
        let credential = PhoneAuthProvider.provider().credential( withVerificationID: verificationID, verificationCode: code)
        
        Auth.auth().signIn(with: credential) { (authResult, error) in
            result(error)
            CurrentState.shared.user = authResult?.user
        }
    }
}
