//
//  LoginInterfaces.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import FirebaseAuth

protocol LoginWireframeInterface: WireframeInterface {
    func routeToRegistration()
}

protocol LoginViewInterface: ViewInterface {
    func loadingView(show: Bool)
}

protocol LoginPresenterInterface: PresenterInterface {
    func showRegistration()
    func login(loginText: String, password: String)
}

protocol LoginInteractorInterface: InteractorInterface {
    func loginWith(username: String, password: String, handler: @escaping (AuthDataResult?, AuthResult?) -> ())
    func loginWith(phoneNumber: String, password: String, handler: @escaping (AuthDataResult?, AuthResult?) -> ())
}
