//
//  LoginViewController.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: LoginPresenterInterface!

    // MARK: - Private properties -


    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        hideKeyboard()
    }
	
    @IBAction func registrationButton(_ sender: UIButton) {
        presenter.showRegistration()
    }
}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
}
