//
//  PhoneEnterPresenter.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PhoneEnterPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: PhoneEnterViewInterface
    private let interactor: PhoneEnterInteractorInterface
    private let wireframe: PhoneEnterWireframeInterface
    
    // MARK: - Lifecycle -
    
    init(view: PhoneEnterViewInterface, interactor: PhoneEnterInteractorInterface, wireframe: PhoneEnterWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension PhoneEnterPresenter: PhoneEnterPresenterInterface {
    
    func getFormattedPhoneNumber(number: String) -> String {
        let cleanPhoneNumber = number.components(separatedBy: CharacterSet.decimalDigits.inverted).joined()
        let mask = "+X (XXX) XXX-XX-XX"
        var result = ""
        var index = cleanPhoneNumber.startIndex
        for ch in mask where index < cleanPhoneNumber.endIndex {
            if ch == "X" {
                result.append(cleanPhoneNumber[index])
                index = cleanPhoneNumber.index(after: index)
            } else {
                result.append(ch)
            }
        }
        view.nextButtonIs(enabled: result.count == mask.count)
        return result
    }
    
    func auth(phoneNumber: String) {
        view.loadingView(show: true)
        interactor.auth(phoneNumber: phoneNumber) { number, verificationID, error in
            if let error = error {
                self.wireframe.showErrorAlert(with: error.localizedDescription)
            } else {
                self.interactor.saveVerificationID(verificationID: verificationID!)
                self.interactor.savePhoneNumber(phoneNumber: phoneNumber)
                self.wireframe.routeToCheckCode(number: number)
            }
            self.view.loadingView(show: false)
        }
    }
    
}
