//
//  RegistrationWireframe.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class RegistrationWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "Registration", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: RegistrationViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = RegistrationInteractor()
        let presenter = RegistrationPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RegistrationWireframe: RegistrationWireframeInterface {
    func routeToCheckCode(number: String) {
        let checkCodeWireframe = CheckCodeWireframe()
        (checkCodeWireframe.viewController as! CheckCodeViewController).number = number
        navigationController?.pushWireframe(checkCodeWireframe)
    }
    
}
