//
//  RegistrationInteractor.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import FirebaseAuth

final class RegistrationInteractor {
    
    var number = ""
    
}

// MARK: - Extensions -

extension RegistrationInteractor: RegistrationInteractorInterface {
    
    func set(number: String) {
        self.number = number
    }
    
    func auth(authResult: @escaping (String, String?, Error?) -> ()) {
        Auth.auth().languageCode = "ru"
        PhoneAuthProvider.provider().verifyPhoneNumber(number, uiDelegate: nil) { (verificationID, error) in
            authResult(self.number, verificationID, error)
        }
    }
    
    func saveVerificationID(verificationID: String) {
        UserDefaults.standard.set(verificationID, forKey: "authVerificationID")
    }
    
}
