//
//  CreateUserViewController.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import FirebaseAuth

final class CreateUserViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: CreateUserPresenterInterface!
    
    @IBOutlet weak var usernameTextField: EnterTextField!
    @IBOutlet weak var emailTextField: EnterTextField!
    @IBOutlet weak var passwordTextField: EnterTextField!
    @IBOutlet weak var repeatPasswordTextField: EnterTextField!
    @IBOutlet weak var roleSegmentedControl: UISegmentedControl!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setTitle(title: "Регистрация")
        presenter.removePreviousControllers()
    }
    
    @IBAction func signInPressed(_ sender: UIButton) {
        guard presenter.isValid(userName: usernameTextField.text!),
            presenter.isValid(email: emailTextField.text!),
            presenter.isValid(password: passwordTextField.text!),
            presenter.isEqual(password: passwordTextField.text!, repeatPassword: repeatPasswordTextField.text!)
            else {return}
        
        presenter.createUser(name: usernameTextField.text!, email: emailTextField.text!, password: passwordTextField.text!, isMaster: roleSegmentedControl!.selectedSegmentIndex == 0 ? false : true)
    }
    
}

// MARK: - Extensions -

extension CreateUserViewController: CreateUserViewInterface {
    func userNameIsNotValid() {
        usernameTextField.setError()
    }
    
    func emainIsNotValid() {
        emailTextField.setError()
    }
    
    func passwordIsNotValid() {
        passwordTextField.setError()
    }
    
    func passwordIsNotEqual() {
        repeatPasswordTextField.setError()
    }
    
    func loadingView(show: Bool) {
        UIUtils.shared.showLoading(view: view, isShow: show)
    }
    
}
