//
//  CreateUserPresenter.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateUserPresenter {
    
    // MARK: - Private properties -
    
    private unowned let view: CreateUserViewInterface
    private let interactor: CreateUserInteractorInterface
    private let wireframe: CreateUserWireframeInterface
    
    // MARK: - Lifecycle -
    
    init(view: CreateUserViewInterface, interactor: CreateUserInteractorInterface, wireframe: CreateUserWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    private func sendNotification() {
        NotificationCenter.default.post(Notification(name: Notification.Name("RegisterCompleted")))
    }
    
    private func createUserDB(uid: String, username: String, email: String, name: String, birthDate: Date, isMaster: Bool) {
        let phoneNumber = CurrentState.shared.phoneNumber!
        interactor.createUserDB(uid: uid, username: username, phoneNumber: phoneNumber, email: email, name: name, birthDate: birthDate, isMaster: isMaster) { error in
            if let error = error {
                self.view.loadingView(show: false)
                self.wireframe.showErrorAlert(with: error.localizedDescription)
                return
            }
            self.wireframe.dismiss(animated: true)
            CurrentState.shared.email = email
            self.sendNotification()
        }
    }
}

// MARK: - Extensions -

extension CreateUserPresenter: CreateUserPresenterInterface {
    func isValid(username: String) -> Bool {
        if !interactor.isValid(username: username) {
            view.userNameIsNotValid()
            wireframe.showAlert(with: "Недопустимое имя пользователя", message: "Имя пользователя должно состоять минимум из 5 символов, включая \".\" и \"_\"")
            return false
        }
        return true
    }
    
    func isValid(email: String) -> Bool {
        if !interactor.isValid(email: email) {
            view.emailIsNotValid()
            wireframe.showAlert(with: "Недопустимый адрес электронной почты", message: "Адрес почты должен быть в формате \"example@mail.com\"")
            return false
        }
        return true
    }
    
    func isValid(firstName: String) -> Bool {
        if !interactor.isValid(firstName: firstName) {
            wireframe.showAlert(with: "Недопустимое имя или фамилия", message: "Имя и фамилия должны содержать в себе только буквы")
            return false
        }
        return true
    }
    
    func isValid(birthDate: String) -> Bool {
        if !interactor.isValid(birthDate: birthDate) {
            view.birthDateIsNotValid()
            wireframe.showAlert(with: "Недопустимая дата рождения", message: "Выберите дату рождения")
            return false
        }
        return true
    }
    
    func isValid(password: String) -> Bool {
        if !interactor.isValid(password: password) {
            view.passwordIsNotValid()
            wireframe.showAlert(with: "Недопустимый пароль", message: "Пароль должен состоять минимум из 6 символов, включая \".\" и \"_\"")
            return false
        }
        return true
    }
    
    func isEqual(password: String, repeatPassword: String) -> Bool {
        if !interactor.isEqual(password: password, repeatPassword: repeatPassword) {
            view.passwordIsNotEqual()
            wireframe.showAlert(with: "Пароли не совпадают", message: "Проверьте правильность ввода паролей")
            return false
        }
        return true
    }
    
    func removePreviousControllers() {
        wireframe.removePreviousControllers()
    }
    
    func createUser(username: String, email: String, name: String, birthDate: String, isMaster: Bool, password: String) {
        view.loadingView(show: true)
        interactor.checkDataExist(email: email, username: username) { (error) in
            if let error = error {
                self.view.loadingView(show: false)
                self.wireframe.showErrorAlert(with: error.localizedDescription)
                return
            }
            self.interactor.createUser(email: email, password: password, isMaster: isMaster) { result, error in
                if let error = error {
                    self.view.loadingView(show: false)
                    self.wireframe.showErrorAlert(with: error.localizedDescription)
                    return
                }
                let dateFormatter = DateFormatter()
                dateFormatter.dateFormat = "dd.MM.yyyy"
                let date = dateFormatter.date(from: birthDate)
                self.createUserDB(uid: result!.user.uid, username: username, email: email, name: name, birthDate: date!, isMaster: isMaster)
            }
        }
    }
}
