//
//  CheckCodePresenter.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CheckCodePresenter {

    // MARK: - Private properties -

    private unowned let view: CheckCodeViewInterface
    private let interactor: CheckCodeInteractorInterface
    private let wireframe: CheckCodeWireframeInterface

    // MARK: - Lifecycle -

    init(view: CheckCodeViewInterface, interactor: CheckCodeInteractorInterface, wireframe: CheckCodeWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CheckCodePresenter: CheckCodePresenterInterface {
    func signIn(code: String) {
        view.loadingView(show: true)
        interactor.signIn(code: code) { error in
            self.view.loadingView(show: false)
            if error != nil {
                self.view.setError()
                self.wireframe.showErrorAlert(with: error?.localizedDescription)
            } else {
                self.wireframe.routeToCreateUser()
            }
        }
    }
}
