//
//  CreateUserViewController.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateUserViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CreateUserPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setTitle(title: "Регистрация")
        presenter.removePreviousControllers()
    }
	
}

// MARK: - Extensions -

extension CreateUserViewController: CreateUserViewInterface {
    
}
