//
//  CreateUserInterfaces.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CreateUserWireframeInterface: WireframeInterface {
    func removePreviousControllers()
}

protocol CreateUserViewInterface: ViewInterface {
}

protocol CreateUserPresenterInterface: PresenterInterface {
    func removePreviousControllers()
}

protocol CreateUserInteractorInterface: InteractorInterface {
}
