//
//  CreateUserInteractor.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CreateUserInteractor {
}

// MARK: - Extensions -

extension CreateUserInteractor: CreateUserInteractorInterface {
}
