//
//  CreateUserWireframe.swift
//  Maniq
//
//  Created by Сергей Гаврилов on 02.02.2020.
//  Copyright (c) 2020 Сергей Гаврилов. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CreateUserWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "CreateUser", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: CreateUserViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = CreateUserInteractor()
        let presenter = CreateUserPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension CreateUserWireframe: CreateUserWireframeInterface {
    func removePreviousControllers() {
        navigationController?.viewControllers.removeAll(where: {
            !($0 is CreateUserViewController)
        })
    }
}
